#config-file
namespace: app-pipeline-example

app:
  name: s2i-sample
  deploymentName: s2i-sample
  deploymentConfigMatch: "s2i-sample"
  version: "v1"

secrets:
  - name: s2i-sample-secrets
    keys:
      - name: EXAMPLE_SECRET
        encoded: false
        value: "abcd"
        
replicaCount: 1

image:
  nameVersion: image-registry.openshift-image-registry.svc:5000/app-pipeline-example/s2i-sample:1.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "s2i-sample"

podSecurityContext: {}

securityContext: {}

ports:
  - containerPort: 8080

environments:
  - name: EXAMPLE_ENV
    value: "teste-envs"

# service
service:
  type: NodePort
  name: http
  port: 8080
  targetPort: 8080

# route
route:
  enabled: true
  name: s2i-sample
  serviceName: s2i-sample
  targetPort: http