{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.route.name }}
  namespace: {{ $.Values.namespace }}
  labels:
{{ include "argocd.defaultLabels" . | indent 4 }}
    app: {{ $.Values.app.name }}

spec:
  host: s2i-sample-app-pipeline-example.apps.ocp4-16.farg.com
  to:
    kind: Service
    name: {{ $.Values.route.serviceName }}
    weight: 100
  port:
    targetPort: {{ $.Values.route.targetPort }}
  tls:
    termination: edge
  wildcardPolicy: None
  
{{- end }}